### PR TITLE
[FEATURE] support putting seq/vec into consul

### PR DESCRIPTION
**Pull request by luhhujbb**

### CODE REVIEW

**Comment by tolitius** [comment]
could you provide a use case where this would help?

for example if I have a list of host names: i.e.
```clojure
["host1.com" "host2.com" "host3.com"]
```
I would actually want it to be stored as such and not as a

```clojure
{:0 "host1.com" :1 "host2.com" :2 "host3.com"}
``` 
map

**Comment by luhhujbb** [comment]
I actually hesitate between this behaviour and the one you describe, ie serialize seqence/vector into JSON array.

Your exemple is pretty simple, and in your specific case, maybe it is better.

But when you vector/sequence contains objects which are themselves nested , not just string, I just follow your way to store map in the consul KV : each level of depth is a path fragment.

**Comment by tolitius** [comment]
I am not sure what you mean by:

> _when you vector/sequence contains objects which are themselves nested , not just string_

1. Can you provide an example of when it would be best to convert a vector of objects to an indexed map?

2. I'd like to keep data as close as possible between an application / configuration and Consul. For example I might have a map of offsets where a key is a topic number and a value is a client offset in that topic:

```clojure
{0 42342, 1 42242, 2 42142}
```

this is a _map_ on both: Consul side and an application side: i.e. it should not be morphed into something else.

**Comment by luhhujbb** [comment]
I've added a function which do the reverse job.

So now you can do this kind of stuff :

```clojure 
(def complicated-map {:my-map {:vec ["a" "b" {:nested-map b}] :map {:a "a" :b "b"}}})
(envoy/map->consul "http://consul:8500/v1/kv" complicacted-map)
(def stored-map (envoy/consul->map "http://consul:8500/v1/kv/my-map")
(= stored-map complicated-map)
true 
```

Your current implementation only support putting vector/sequence which are in a map via edn serialization which is not compatible with others languages.

If another consul client written in another language want to watch only a single item of a list it is currently not possible, or it has to implement an edn deserializer.

Sometimes we pass lazy seq to be stored and only serialized reference of the lazy-seq is store into consul which is not really usable.

If you want your behavior, you can do with cheshire : 

```clojure 
(def complicated-map {:my-map {:vec (json/generate-string 
                                          ["a" "b" {:nested-map b}]) 
                               :map {:a "a" :b "b"}}})
(envoy/map->consul "http://consul:8500/v1/kv" complicacted-map)
(def stored-map (envoy/consul->map "http://consul:8500/v1/kv/my-map")
(= stored-map complicated-map)
true
```
This is the way consul recommend to store things : as scalar or as json

But I personally find this way less elegant, because you can also do :
```clojure 
(def complicated-map
   {:my-map 
      (json/generate-string {:vec ["a" "b" {:nested-map b}] :map {:a "a" :b "b"}})})
```
How do you choose the right depth ? Consul client doesn't have to decide the depth of serialization.

My implementation provide a default way to store clojure map in a compatible way with other language and allow to make atomic update of complex element even when they are in vector/sequence.

 Anyway this is your repo !

**Comment by luhhujbb** [comment]
I perfectly understand your point. 

Some of our soft have to update atomically some field into map which are into a vec, even it is odd.

Let me propose you a new version with :
 - json serialization by default
 - lazy-seq to list conversion (so that we don't store lazyobject ref into consul) 

I will rewrite some part of our soft to update

**Pull request closed without merging**
